-- MySQL Script generated by MySQL Workbench
-- 03/01/19 13:57:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `playerId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NULL,
  `points` INT NULL,
  `activeTurn` TINYINT(1) NOT NULL DEFAULT 0,
  `password` VARCHAR(45) NULL,
  `female` TINYINT(1) NULL,
  `birthyear` INT NULL,
  PRIMARY KEY (`playerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`categoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Questions` (
  `questionId` INT NOT NULL AUTO_INCREMENT,
  `questionText` TEXT NULL,
  `categoryId` INT NOT NULL,
  PRIMARY KEY (`questionId`),
  CONSTRAINT `categoryId`
    FOREIGN KEY (`questionId`)
    REFERENCES `mydb`.`Category` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alternative` (
  `answerId` INT NOT NULL AUTO_INCREMENT,
  `presidentId` INT NULL,
  `score` INT NULL,
  `questionId` INT NOT NULL,
  PRIMARY KEY (`answerId`, `presidentId`),
  INDEX `questionId_idx` (`questionId` ASC),
  CONSTRAINT `questionId`
    FOREIGN KEY (`questionId`)
    REFERENCES `mydb`.`Questions` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `gameId` INT NOT NULL AUTO_INCREMENT,
  `player1` INT NULL,
  `player2` INT NULL,
  `p1Points` INT NULL,
  `p2Points` INT NULL,
  `categoryId` INT NULL,
  `question1` INT NULL,
  `question2` INT NULL,
  `question3` INT NULL,
  PRIMARY KEY (`gameId`),
  INDEX `player1_idx` (`player1` ASC),
  INDEX `player2_idx` (`player2` ASC),
  INDEX `question1_idx` (`question1` ASC),
  INDEX `question2_idx` (`question2` ASC),
  INDEX `question3_idx` (`question3` ASC),
  CONSTRAINT `player1`
    FOREIGN KEY (`player1`)
    REFERENCES `mydb`.`Player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `player2`
    FOREIGN KEY (`player2`)
    REFERENCES `mydb`.`Player` (`playerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Category` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question1`
    FOREIGN KEY (`question1`)
    REFERENCES `mydb`.`Questions` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question2`
    FOREIGN KEY (`question2`)
    REFERENCES `mydb`.`Questions` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `question3`
    FOREIGN KEY (`question3`)
    REFERENCES `mydb`.`Questions` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;